server:
  port: 9997
spring:
  quartz:
    #相关属性配置
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    #数据库方式
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
  datasource:
    password: 123456
    username: root
    url: jdbc:mysql://localhost:3306/moguding?characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.qq.com
    username: 2174521520@qq.com
    password: jszbklspyintdijc
    protocol: smtp
    default-encoding: UTF-8
mybatis:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.qianmua.dao

mail:
  send-mail-from: 2174521520@qq.com
  send-mail-to: 2674521520@qq.com
  mogu-send-title: 蘑菇钉自动签到

mogu.service:
  sign-uri: https://api.moguding.net:9000